name: Update Modify
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Update README.md
        id: update_readme
        run: |
          time_zone_diff=8
          last_modify_time_badge_content=`date -d "$time_zone_diff hours" +"%Y--%m--%d_%H:%M:%S"`
          sed -i -r "s#last_modify-[0-9]{4}--[0-9]{1,2}--[0-9]{1,2}_([0-9]{2}:){2}[0-9]{2}#last_modify-${last_modify_time_badge_content}#g" README.md
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: master
          default_author: user_info
